// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) import OpenAPIRuntime
#if os(Linux)
@preconcurrency import struct Foundation.URL
@preconcurrency import struct Foundation.Data
@preconcurrency import struct Foundation.Date
#else
import struct Foundation.URL
import struct Foundation.Data
import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// Gets a list of profiles.
    ///
    /// Note that this operation does not return a response unless the current account has created at least one campaign using the advertising console.
    ///
    /// - Remark: HTTP `GET /v2/profiles`.
    /// - Remark: Generated from `#/paths//v2/profiles/get(listProfiles)`.
    func listProfiles(_ input: Operations.listProfiles.Input) async throws -> Operations.listProfiles.Output
    /// Update the daily budget for one or more profiles.
    ///
    /// Note that this operation is only used for Sellers using Sponsored Products. This operation is not enabled for vendor type accounts.
    ///
    /// - Remark: HTTP `PUT /v2/profiles`.
    /// - Remark: Generated from `#/paths//v2/profiles/put(updateProfiles)`.
    func updateProfiles(_ input: Operations.updateProfiles.Input) async throws -> Operations.updateProfiles.Output
    /// Gets a profile specified by identifier.
    ///
    /// This operation does not return a response unless the current account has created at least one campaign using the advertising console.
    ///
    /// - Remark: HTTP `GET /v2/profiles/{profileId}`.
    /// - Remark: Generated from `#/paths//v2/profiles/{profileId}/get(getProfileById)`.
    func getProfileById(_ input: Operations.getProfileById.Input) async throws -> Operations.getProfileById.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// Gets a list of profiles.
    ///
    /// Note that this operation does not return a response unless the current account has created at least one campaign using the advertising console.
    ///
    /// - Remark: HTTP `GET /v2/profiles`.
    /// - Remark: Generated from `#/paths//v2/profiles/get(listProfiles)`.
    public func listProfiles(
        query: Operations.listProfiles.Input.Query = .init(),
        headers: Operations.listProfiles.Input.Headers
    ) async throws -> Operations.listProfiles.Output {
        try await listProfiles(Operations.listProfiles.Input(
            query: query,
            headers: headers
        ))
    }
    /// Update the daily budget for one or more profiles.
    ///
    /// Note that this operation is only used for Sellers using Sponsored Products. This operation is not enabled for vendor type accounts.
    ///
    /// - Remark: HTTP `PUT /v2/profiles`.
    /// - Remark: Generated from `#/paths//v2/profiles/put(updateProfiles)`.
    public func updateProfiles(
        headers: Operations.updateProfiles.Input.Headers,
        body: Operations.updateProfiles.Input.Body? = nil
    ) async throws -> Operations.updateProfiles.Output {
        try await updateProfiles(Operations.updateProfiles.Input(
            headers: headers,
            body: body
        ))
    }
    /// Gets a profile specified by identifier.
    ///
    /// This operation does not return a response unless the current account has created at least one campaign using the advertising console.
    ///
    /// - Remark: HTTP `GET /v2/profiles/{profileId}`.
    /// - Remark: Generated from `#/paths//v2/profiles/{profileId}/get(getProfileById)`.
    public func getProfileById(
        path: Operations.getProfileById.Input.Path,
        headers: Operations.getProfileById.Input.Headers
    ) async throws -> Operations.getProfileById.Output {
        try await getProfileById(Operations.getProfileById.Input(
            path: path,
            headers: headers
        ))
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {
    /// North America
    public enum Server1 {
        /// North America
        public static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "https://advertising-api.amazon.com",
                variables: []
            )
        }
    }
    /// North America
    @available(*, deprecated, renamed: "Servers.Server1.url")
    public static func server1() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "https://advertising-api.amazon.com",
            variables: []
        )
    }
    /// Europe
    public enum Server2 {
        /// Europe
        public static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "https://advertising-api-eu.amazon.com",
                variables: []
            )
        }
    }
    /// Europe
    @available(*, deprecated, renamed: "Servers.Server2.url")
    public static func server2() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "https://advertising-api-eu.amazon.com",
            variables: []
        )
    }
    /// Far East
    public enum Server3 {
        /// Far East
        public static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "https://advertising-api-fe.amazon.com",
                variables: []
            )
        }
    }
    /// Far East
    @available(*, deprecated, renamed: "Servers.Server3.url")
    public static func server3() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "https://advertising-api-fe.amazon.com",
            variables: []
        )
    }
}

/// Types generated from the components section of the OpenAPI document.
public enum Components {
    /// Types generated from the `#/components/schemas` section of the OpenAPI document.
    public enum Schemas {
        /// The `seller` and `vendor` account types are associated with Sponsored Ads APIs. The `agency` account type is associated with DSP and Data Provider APIs.
        ///
        /// - Remark: Generated from `#/components/schemas/AccountType`.
        @frozen public enum AccountType: String, Codable, Hashable, Sendable, CaseIterable {
            case vendor = "vendor"
            case seller = "seller"
            case agency = "agency"
        }
        /// - Remark: Generated from `#/components/schemas/AccountInfo`.
        public struct AccountInfo: Codable, Hashable, Sendable {
            /// The identifier of the marketplace to which the account is associated.
            ///
            /// - Remark: Generated from `#/components/schemas/AccountInfo/marketplaceStringId`.
            public var marketplaceStringId: Swift.String?
            /// Identifier for sellers and vendors. Note that this value is not unique and may be the same across marketplace.
            ///
            /// - Remark: Generated from `#/components/schemas/AccountInfo/id`.
            public var id: Swift.String?
            /// - Remark: Generated from `#/components/schemas/AccountInfo/type`.
            public var _type: Components.Schemas.AccountType?
            /// Account name.
            ///
            /// - Remark: Generated from `#/components/schemas/AccountInfo/name`.
            public var name: Swift.String?
            /// The account subtype.
            ///
            /// - Remark: Generated from `#/components/schemas/AccountInfo/subType`.
            @frozen public enum subTypePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case KDP_AUTHOR = "KDP_AUTHOR"
                case AMAZON_ATTRIBUTION = "AMAZON_ATTRIBUTION"
            }
            /// The account subtype.
            ///
            /// - Remark: Generated from `#/components/schemas/AccountInfo/subType`.
            public var subType: Components.Schemas.AccountInfo.subTypePayload?
            /// Only present for Vendors, this returns whether the Advertiser has set up a valid payment method or not.
            ///
            /// - Remark: Generated from `#/components/schemas/AccountInfo/validPaymentMethod`.
            public var validPaymentMethod: Swift.Bool?
            /// Creates a new `AccountInfo`.
            ///
            /// - Parameters:
            ///   - marketplaceStringId: The identifier of the marketplace to which the account is associated.
            ///   - id: Identifier for sellers and vendors. Note that this value is not unique and may be the same across marketplace.
            ///   - _type:
            ///   - name: Account name.
            ///   - subType: The account subtype.
            ///   - validPaymentMethod: Only present for Vendors, this returns whether the Advertiser has set up a valid payment method or not.
            public init(
                marketplaceStringId: Swift.String? = nil,
                id: Swift.String? = nil,
                _type: Components.Schemas.AccountType? = nil,
                name: Swift.String? = nil,
                subType: Components.Schemas.AccountInfo.subTypePayload? = nil,
                validPaymentMethod: Swift.Bool? = nil
            ) {
                self.marketplaceStringId = marketplaceStringId
                self.id = id
                self._type = _type
                self.name = name
                self.subType = subType
                self.validPaymentMethod = validPaymentMethod
            }
            public enum CodingKeys: String, CodingKey {
                case marketplaceStringId
                case id
                case _type = "type"
                case name
                case subType
                case validPaymentMethod
            }
        }
        /// The countryCode for a given country
        /// |Region|`countryCode`|Country Name|
        /// |------|-----|-------|
        /// |NA|BR|Brazil|
        /// |NA|CA|Canada|
        /// |NA|MX|Mexico|
        /// |NA|US|United States|
        /// |EU|AE|United Arab Emirates|
        /// |EU|BE|Belgium|
        /// |EU|DE|Germany|
        /// |EU|EG|Egypt|
        /// |EU|ES|Spain|
        /// |EU|FR|France|
        /// |EU|IE|Ireland|
        /// |EU|IN|India|
        /// |EU|IT|Italy|
        /// |EU|NL|The Netherlands|
        /// |EU|PL|Poland|
        /// |EU|SA|Saudi Arabia|
        /// |EU|SE|Sweden|
        /// |EU|TR|Turkey|
        /// |EU|UK|United Kingdom|
        /// |EU|ZA| South Africa |
        /// |FE|AU|Australia|
        /// |FE|JP|Japan|
        /// |FE|SG|Singapore|
        ///
        /// - Remark: Generated from `#/components/schemas/countryCode`.
        @frozen public enum countryCode: String, Codable, Hashable, Sendable, CaseIterable {
            case BR = "BR"
            case CA = "CA"
            case MX = "MX"
            case US = "US"
            case AE = "AE"
            case BE = "BE"
            case DE = "DE"
            case EG = "EG"
            case ES = "ES"
            case FR = "FR"
            case IE = "IE"
            case IN = "IN"
            case IT = "IT"
            case NL = "NL"
            case PL = "PL"
            case SA = "SA"
            case SE = "SE"
            case TR = "TR"
            case UK = "UK"
            case AU = "AU"
            case JP = "JP"
            case SG = "SG"
            case ZA = "ZA"
        }
        /// - Remark: Generated from `#/components/schemas/Profile`.
        public struct Profile: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/Profile/profileId`.
            public var profileId: Swift.Int64?
            /// - Remark: Generated from `#/components/schemas/Profile/countryCode`.
            public var countryCode: Components.Schemas.countryCode?
            /// The currency used for all monetary values for entities under this profile.
            /// |Region|`countryCode`|Country Name|`currencyCode`|
            /// |-----|------|------|------|
            /// |NA|BR|Brazil|BRL|
            /// |NA|CA|Canada|CAD|
            /// |NA|MX|Mexico|MXN|
            /// |NA|US|United States|USD|
            /// |EU|AE|United Arab Emirates|AED|
            /// |EU|BE|Belgium|EUR|
            /// |EU|DE|Germany|EUR|
            /// |EU|EG|Egypt|EGP|
            /// |EU|ES|Spain|EUR|
            /// |EU|FR|France|EUR|
            /// |EU|IE|Ireland|EUR|
            /// |EU|IN|India|INR|
            /// |EU|IT|Italy|EUR|
            /// |EU|NL|The Netherlands|EUR|
            /// |EU|PL|Poland|PLN|
            /// |EU|SA|Saudi Arabia|SAR|
            /// |EU|SE|Sweden|SEK|
            /// |EU|TR|Turkey|TRY|
            /// |EU|UK|United Kingdom|GBP|
            /// |EU|ZA| South Africa | ZAR|
            /// |FE|AU|Australia|AUD|
            /// |FE|JP|Japan|JPY|
            /// |FE|SG|Singapore|SGD|
            ///
            /// - Remark: Generated from `#/components/schemas/Profile/currencyCode`.
            @frozen public enum currencyCodePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case BRL = "BRL"
                case CAD = "CAD"
                case MXN = "MXN"
                case USD = "USD"
                case AED = "AED"
                case EUR = "EUR"
                case EGP = "EGP"
                case INR = "INR"
                case PLN = "PLN"
                case SAR = "SAR"
                case SEK = "SEK"
                case TRY = "TRY"
                case GBP = "GBP"
                case AUD = "AUD"
                case JPY = "JPY"
                case SGD = "SGD"
                case ZAR = "ZAR"
            }
            /// The currency used for all monetary values for entities under this profile.
            /// |Region|`countryCode`|Country Name|`currencyCode`|
            /// |-----|------|------|------|
            /// |NA|BR|Brazil|BRL|
            /// |NA|CA|Canada|CAD|
            /// |NA|MX|Mexico|MXN|
            /// |NA|US|United States|USD|
            /// |EU|AE|United Arab Emirates|AED|
            /// |EU|BE|Belgium|EUR|
            /// |EU|DE|Germany|EUR|
            /// |EU|EG|Egypt|EGP|
            /// |EU|ES|Spain|EUR|
            /// |EU|FR|France|EUR|
            /// |EU|IE|Ireland|EUR|
            /// |EU|IN|India|INR|
            /// |EU|IT|Italy|EUR|
            /// |EU|NL|The Netherlands|EUR|
            /// |EU|PL|Poland|PLN|
            /// |EU|SA|Saudi Arabia|SAR|
            /// |EU|SE|Sweden|SEK|
            /// |EU|TR|Turkey|TRY|
            /// |EU|UK|United Kingdom|GBP|
            /// |EU|ZA| South Africa | ZAR|
            /// |FE|AU|Australia|AUD|
            /// |FE|JP|Japan|JPY|
            /// |FE|SG|Singapore|SGD|
            ///
            /// - Remark: Generated from `#/components/schemas/Profile/currencyCode`.
            public var currencyCode: Components.Schemas.Profile.currencyCodePayload?
            /// Note that this field applies to Sponsored Product campaigns for seller type accounts only. Not supported for vendor type accounts.
            ///
            /// - Remark: Generated from `#/components/schemas/Profile/dailyBudget`.
            public var dailyBudget: Swift.Double?
            /// The time zone used for all date-based campaign management and reporting.
            /// |Region|`countryCode`|Country Name|`timezone`|
            /// |------|-----|-----|------|
            /// |NA|BR|Brazil|America/Sao_Paulo|
            /// |NA|CA|Canada|America/Los_Angeles|
            /// |NA|MX|Mexico|America/Los_Angeles|
            /// |NA|US|United States|America/Los_Angeles|
            /// |EU|AE|United Arab Emirates|Asia/Dubai|
            /// |EU|BE|Belgium|Europe/Brussels|
            /// |EU|DE|Germany|Europe/Paris|
            /// |EU|EG|Egypt|Africa/Cairo|
            /// |EU|ES|Spain|Europe/Paris|
            /// |EU|FR|France|Europe/Paris|
            /// |EU|IE|Ireland|Europe/Dublin|
            /// |EU|IN|India|Asia/Kolkata|
            /// |EU|IT|Italy|Europe/Paris|
            /// |EU|NL|The Netherlands|Europe/Amsterdam|
            /// |EU|PL|Poland|Europe/Warsaw|
            /// |EU|SA|Saudi Arabia|Asia/Riyadh|
            /// |EU|SE|Sweden|Europe/Stockholm|
            /// |EU|TR|Turkey|Europe/Istanbul|
            /// |EU|UK|United Kingdom|Europe/London|
            /// |EU|ZA| South Africa | Africa/Johannesburg |
            /// |FE|AU|Australia|Australia/Sydney|
            /// |FE|JP|Japan|Asia/Tokyo|
            /// |FE|SG|Singapore|Asia/Singapore|
            ///
            /// - Remark: Generated from `#/components/schemas/Profile/timezone`.
            @frozen public enum timezonePayload: String, Codable, Hashable, Sendable, CaseIterable {
                case Africa_sol_Cairo = "Africa/Cairo"
                case America_sol_Sao_Paulo = "America/Sao_Paulo"
                case America_sol_Los_Angeles = "America/Los_Angeles"
                case Asia_sol_Dubai = "Asia/Dubai"
                case Asia_sol_Kolkata = "Asia/Kolkata"
                case Asia_sol_Riyadh = "Asia/Riyadh"
                case Asia_sol_Singapore = "Asia/Singapore"
                case Asia_sol_Tokyo = "Asia/Tokyo"
                case Australia_sol_Sydney = "Australia/Sydney"
                case Europe_sol_Amsterdam = "Europe/Amsterdam"
                case Europe_sol_Dublin = "Europe/Dublin"
                case Europe_sol_Istanbul = "Europe/Istanbul"
                case Europe_sol_London = "Europe/London"
                case Europe_sol_Paris = "Europe/Paris"
                case Europe_sol_Stockholm = "Europe/Stockholm"
                case Europe_sol_Warsaw = "Europe/Warsaw"
                case Europe_sol_Brussels = "Europe/Brussels"
                case Africa_sol_Johannesburg = "Africa/Johannesburg"
            }
            /// The time zone used for all date-based campaign management and reporting.
            /// |Region|`countryCode`|Country Name|`timezone`|
            /// |------|-----|-----|------|
            /// |NA|BR|Brazil|America/Sao_Paulo|
            /// |NA|CA|Canada|America/Los_Angeles|
            /// |NA|MX|Mexico|America/Los_Angeles|
            /// |NA|US|United States|America/Los_Angeles|
            /// |EU|AE|United Arab Emirates|Asia/Dubai|
            /// |EU|BE|Belgium|Europe/Brussels|
            /// |EU|DE|Germany|Europe/Paris|
            /// |EU|EG|Egypt|Africa/Cairo|
            /// |EU|ES|Spain|Europe/Paris|
            /// |EU|FR|France|Europe/Paris|
            /// |EU|IE|Ireland|Europe/Dublin|
            /// |EU|IN|India|Asia/Kolkata|
            /// |EU|IT|Italy|Europe/Paris|
            /// |EU|NL|The Netherlands|Europe/Amsterdam|
            /// |EU|PL|Poland|Europe/Warsaw|
            /// |EU|SA|Saudi Arabia|Asia/Riyadh|
            /// |EU|SE|Sweden|Europe/Stockholm|
            /// |EU|TR|Turkey|Europe/Istanbul|
            /// |EU|UK|United Kingdom|Europe/London|
            /// |EU|ZA| South Africa | Africa/Johannesburg |
            /// |FE|AU|Australia|Australia/Sydney|
            /// |FE|JP|Japan|Asia/Tokyo|
            /// |FE|SG|Singapore|Asia/Singapore|
            ///
            /// - Remark: Generated from `#/components/schemas/Profile/timezone`.
            public var timezone: Components.Schemas.Profile.timezonePayload?
            /// - Remark: Generated from `#/components/schemas/Profile/accountInfo`.
            public var accountInfo: Components.Schemas.AccountInfo?
            /// Creates a new `Profile`.
            ///
            /// - Parameters:
            ///   - profileId:
            ///   - countryCode:
            ///   - currencyCode: The currency used for all monetary values for entities under this profile.
            ///   - dailyBudget: Note that this field applies to Sponsored Product campaigns for seller type accounts only. Not supported for vendor type accounts.
            ///   - timezone: The time zone used for all date-based campaign management and reporting.
            ///   - accountInfo:
            public init(
                profileId: Swift.Int64? = nil,
                countryCode: Components.Schemas.countryCode? = nil,
                currencyCode: Components.Schemas.Profile.currencyCodePayload? = nil,
                dailyBudget: Swift.Double? = nil,
                timezone: Components.Schemas.Profile.timezonePayload? = nil,
                accountInfo: Components.Schemas.AccountInfo? = nil
            ) {
                self.profileId = profileId
                self.countryCode = countryCode
                self.currencyCode = currencyCode
                self.dailyBudget = dailyBudget
                self.timezone = timezone
                self.accountInfo = accountInfo
            }
            public enum CodingKeys: String, CodingKey {
                case profileId
                case countryCode
                case currencyCode
                case dailyBudget
                case timezone
                case accountInfo
            }
        }
        /// - Remark: Generated from `#/components/schemas/ProfileResponse`.
        public struct ProfileResponse: Codable, Hashable, Sendable {
            /// - Remark: Generated from `#/components/schemas/ProfileResponse/profileId`.
            public var profileId: Swift.Int64?
            /// - Remark: Generated from `#/components/schemas/ProfileResponse/code`.
            public var code: Swift.String?
            /// - Remark: Generated from `#/components/schemas/ProfileResponse/details`.
            public var details: Swift.String?
            /// Creates a new `ProfileResponse`.
            ///
            /// - Parameters:
            ///   - profileId:
            ///   - code:
            ///   - details:
            public init(
                profileId: Swift.Int64? = nil,
                code: Swift.String? = nil,
                details: Swift.String? = nil
            ) {
                self.profileId = profileId
                self.code = code
                self.details = details
            }
            public enum CodingKeys: String, CodingKey {
                case profileId
                case code
                case details
            }
        }
    }
    /// Types generated from the `#/components/parameters` section of the OpenAPI document.
    public enum Parameters {}
    /// Types generated from the `#/components/requestBodies` section of the OpenAPI document.
    public enum RequestBodies {}
    /// Types generated from the `#/components/responses` section of the OpenAPI document.
    public enum Responses {}
    /// Types generated from the `#/components/headers` section of the OpenAPI document.
    public enum Headers {}
}

/// API operations, with input and output types, generated from `#/paths` in the OpenAPI document.
public enum Operations {
    /// Gets a list of profiles.
    ///
    /// Note that this operation does not return a response unless the current account has created at least one campaign using the advertising console.
    ///
    /// - Remark: HTTP `GET /v2/profiles`.
    /// - Remark: Generated from `#/paths//v2/profiles/get(listProfiles)`.
    public enum listProfiles {
        public static let id: Swift.String = "listProfiles"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/v2/profiles/GET/query`.
            public struct Query: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v2/profiles/GET/query/apiProgram`.
                @frozen public enum apiProgramPayload: String, Codable, Hashable, Sendable, CaseIterable {
                    case billing = "billing"
                    case campaign = "campaign"
                    case paymentMethod = "paymentMethod"
                    case store = "store"
                    case report = "report"
                    case account = "account"
                    case posts = "posts"
                }
                /// Filters response to include profiles that have permissions for the specified Advertising API program only. Setting `apiProgram=billing` filters the response to include only profiles to which the user and application associated with the access token have permission to view or edit billing information.
                ///
                /// - Remark: Generated from `#/paths/v2/profiles/GET/query/apiProgram`.
                public var apiProgram: Operations.listProfiles.Input.Query.apiProgramPayload?
                /// - Remark: Generated from `#/paths/v2/profiles/GET/query/accessLevel`.
                @frozen public enum accessLevelPayload: String, Codable, Hashable, Sendable, CaseIterable {
                    case edit = "edit"
                    case view = "view"
                }
                /// Filters response to include profiles that have specified permissions for the specified Advertising API program only. Currently, the only supported access level is `view` and `edit`. Setting `accessLevel=view` filters the response to include only profiles to which the user and application associated with the access token have view permission to the provided api program.
                ///
                /// - Remark: Generated from `#/paths/v2/profiles/GET/query/accessLevel`.
                public var accessLevel: Operations.listProfiles.Input.Query.accessLevelPayload?
                /// - Remark: Generated from `#/paths/v2/profiles/GET/query/profileTypeFilter`.
                @frozen public enum profileTypeFilterPayload: String, Codable, Hashable, Sendable, CaseIterable {
                    case seller = "seller"
                    case vendor = "vendor"
                    case agency = "agency"
                }
                /// Filters response to include profiles that are of the specified types in the comma-delimited list. Default is all types. Note that this filter performs an inclusive AND operation on the types.
                ///
                /// - Remark: Generated from `#/paths/v2/profiles/GET/query/profileTypeFilter`.
                public var profileTypeFilter: Operations.listProfiles.Input.Query.profileTypeFilterPayload?
                /// - Remark: Generated from `#/paths/v2/profiles/GET/query/validPaymentMethodFilter`.
                @frozen public enum validPaymentMethodFilterPayload: String, Codable, Hashable, Sendable, CaseIterable {
                    case _true = "true"
                    case _false = "false"
                }
                /// Filter response to include profiles that have valid payment methods. Default is to include all profiles. Setting this filter to `true` returns only profiles with either no `validPaymentMethod` field, or the `validPaymentMethod` field set to `true`.  Setting this to `false` returns profiles with the `validPaymentMethod` field set to `false` only.
                ///
                /// - Remark: Generated from `#/paths/v2/profiles/GET/query/validPaymentMethodFilter`.
                public var validPaymentMethodFilter: Operations.listProfiles.Input.Query.validPaymentMethodFilterPayload?
                /// Creates a new `Query`.
                ///
                /// - Parameters:
                ///   - apiProgram: Filters response to include profiles that have permissions for the specified Advertising API program only. Setting `apiProgram=billing` filters the response to include only profiles to which the user and application associated with the access token have permission to view or edit billing information.
                ///   - accessLevel: Filters response to include profiles that have specified permissions for the specified Advertising API program only. Currently, the only supported access level is `view` and `edit`. Setting `accessLevel=view` filters the response to include only profiles to which the user and application associated with the access token have view permission to the provided api program.
                ///   - profileTypeFilter: Filters response to include profiles that are of the specified types in the comma-delimited list. Default is all types. Note that this filter performs an inclusive AND operation on the types.
                ///   - validPaymentMethodFilter: Filter response to include profiles that have valid payment methods. Default is to include all profiles. Setting this filter to `true` returns only profiles with either no `validPaymentMethod` field, or the `validPaymentMethod` field set to `true`.  Setting this to `false` returns profiles with the `validPaymentMethod` field set to `false` only.
                public init(
                    apiProgram: Operations.listProfiles.Input.Query.apiProgramPayload? = nil,
                    accessLevel: Operations.listProfiles.Input.Query.accessLevelPayload? = nil,
                    profileTypeFilter: Operations.listProfiles.Input.Query.profileTypeFilterPayload? = nil,
                    validPaymentMethodFilter: Operations.listProfiles.Input.Query.validPaymentMethodFilterPayload? = nil
                ) {
                    self.apiProgram = apiProgram
                    self.accessLevel = accessLevel
                    self.profileTypeFilter = profileTypeFilter
                    self.validPaymentMethodFilter = validPaymentMethodFilter
                }
            }
            public var query: Operations.listProfiles.Input.Query
            /// - Remark: Generated from `#/paths/v2/profiles/GET/header`.
            public struct Headers: Sendable, Hashable {
                /// The identifier of a client associated with a "Login with Amazon" account.
                ///
                /// - Remark: Generated from `#/paths/v2/profiles/GET/header/Amazon-Advertising-API-ClientId`.
                public var Amazon_hyphen_Advertising_hyphen_API_hyphen_ClientId: Swift.String
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.listProfiles.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - Amazon_hyphen_Advertising_hyphen_API_hyphen_ClientId: The identifier of a client associated with a "Login with Amazon" account.
                ///   - accept:
                public init(
                    Amazon_hyphen_Advertising_hyphen_API_hyphen_ClientId: Swift.String,
                    accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.listProfiles.AcceptableContentType>] = .defaultValues()
                ) {
                    self.Amazon_hyphen_Advertising_hyphen_API_hyphen_ClientId = Amazon_hyphen_Advertising_hyphen_API_hyphen_ClientId
                    self.accept = accept
                }
            }
            public var headers: Operations.listProfiles.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - query:
            ///   - headers:
            public init(
                query: Operations.listProfiles.Input.Query = .init(),
                headers: Operations.listProfiles.Input.Headers
            ) {
                self.query = query
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v2/profiles/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v2/profiles/GET/responses/200/content/application\/json`.
                    case json([Components.Schemas.Profile])
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: [Components.Schemas.Profile] {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.listProfiles.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.listProfiles.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Success.
            ///
            /// - Remark: Generated from `#/paths//v2/profiles/get(listProfiles)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.listProfiles.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.listProfiles.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// Update the daily budget for one or more profiles.
    ///
    /// Note that this operation is only used for Sellers using Sponsored Products. This operation is not enabled for vendor type accounts.
    ///
    /// - Remark: HTTP `PUT /v2/profiles`.
    /// - Remark: Generated from `#/paths//v2/profiles/put(updateProfiles)`.
    public enum updateProfiles {
        public static let id: Swift.String = "updateProfiles"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/v2/profiles/PUT/header`.
            public struct Headers: Sendable, Hashable {
                /// The identifier of a client associated with a "Login with Amazon" account.
                ///
                /// - Remark: Generated from `#/paths/v2/profiles/PUT/header/Amazon-Advertising-API-ClientId`.
                public var Amazon_hyphen_Advertising_hyphen_API_hyphen_ClientId: Swift.String
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.updateProfiles.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - Amazon_hyphen_Advertising_hyphen_API_hyphen_ClientId: The identifier of a client associated with a "Login with Amazon" account.
                ///   - accept:
                public init(
                    Amazon_hyphen_Advertising_hyphen_API_hyphen_ClientId: Swift.String,
                    accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.updateProfiles.AcceptableContentType>] = .defaultValues()
                ) {
                    self.Amazon_hyphen_Advertising_hyphen_API_hyphen_ClientId = Amazon_hyphen_Advertising_hyphen_API_hyphen_ClientId
                    self.accept = accept
                }
            }
            public var headers: Operations.updateProfiles.Input.Headers
            /// - Remark: Generated from `#/paths/v2/profiles/PUT/requestBody`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v2/profiles/PUT/requestBody/content/application\/json`.
                case json([Components.Schemas.Profile])
            }
            public var body: Operations.updateProfiles.Input.Body?
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - headers:
            ///   - body:
            public init(
                headers: Operations.updateProfiles.Input.Headers,
                body: Operations.updateProfiles.Input.Body? = nil
            ) {
                self.headers = headers
                self.body = body
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v2/profiles/PUT/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v2/profiles/PUT/responses/200/content/application\/json`.
                    case json([Components.Schemas.ProfileResponse])
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: [Components.Schemas.ProfileResponse] {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.updateProfiles.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.updateProfiles.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// success
            ///
            /// - Remark: Generated from `#/paths//v2/profiles/put(updateProfiles)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.updateProfiles.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.updateProfiles.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
    /// Gets a profile specified by identifier.
    ///
    /// This operation does not return a response unless the current account has created at least one campaign using the advertising console.
    ///
    /// - Remark: HTTP `GET /v2/profiles/{profileId}`.
    /// - Remark: Generated from `#/paths//v2/profiles/{profileId}/get(getProfileById)`.
    public enum getProfileById {
        public static let id: Swift.String = "getProfileById"
        public struct Input: Sendable, Hashable {
            /// - Remark: Generated from `#/paths/v2/profiles/{profileId}/GET/path`.
            public struct Path: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v2/profiles/{profileId}/GET/path/profileId`.
                public var profileId: Swift.Int64
                /// Creates a new `Path`.
                ///
                /// - Parameters:
                ///   - profileId:
                public init(profileId: Swift.Int64) {
                    self.profileId = profileId
                }
            }
            public var path: Operations.getProfileById.Input.Path
            /// - Remark: Generated from `#/paths/v2/profiles/{profileId}/GET/header`.
            public struct Headers: Sendable, Hashable {
                /// The identifier of a client associated with a "Login with Amazon" account.
                ///
                /// - Remark: Generated from `#/paths/v2/profiles/{profileId}/GET/header/Amazon-Advertising-API-ClientId`.
                public var Amazon_hyphen_Advertising_hyphen_API_hyphen_ClientId: Swift.String
                public var accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.getProfileById.AcceptableContentType>]
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - Amazon_hyphen_Advertising_hyphen_API_hyphen_ClientId: The identifier of a client associated with a "Login with Amazon" account.
                ///   - accept:
                public init(
                    Amazon_hyphen_Advertising_hyphen_API_hyphen_ClientId: Swift.String,
                    accept: [OpenAPIRuntime.AcceptHeaderContentType<Operations.getProfileById.AcceptableContentType>] = .defaultValues()
                ) {
                    self.Amazon_hyphen_Advertising_hyphen_API_hyphen_ClientId = Amazon_hyphen_Advertising_hyphen_API_hyphen_ClientId
                    self.accept = accept
                }
            }
            public var headers: Operations.getProfileById.Input.Headers
            /// Creates a new `Input`.
            ///
            /// - Parameters:
            ///   - path:
            ///   - headers:
            public init(
                path: Operations.getProfileById.Input.Path,
                headers: Operations.getProfileById.Input.Headers
            ) {
                self.path = path
                self.headers = headers
            }
        }
        @frozen public enum Output: Sendable, Hashable {
            public struct Ok: Sendable, Hashable {
                /// - Remark: Generated from `#/paths/v2/profiles/{profileId}/GET/responses/200/content`.
                @frozen public enum Body: Sendable, Hashable {
                    /// - Remark: Generated from `#/paths/v2/profiles/{profileId}/GET/responses/200/content/application\/json`.
                    case json(Components.Schemas.Profile)
                    /// The associated value of the enum case if `self` is `.json`.
                    ///
                    /// - Throws: An error if `self` is not `.json`.
                    /// - SeeAlso: `.json`.
                    public var json: Components.Schemas.Profile {
                        get throws {
                            switch self {
                            case let .json(body):
                                return body
                            }
                        }
                    }
                }
                /// Received HTTP response body
                public var body: Operations.getProfileById.Output.Ok.Body
                /// Creates a new `Ok`.
                ///
                /// - Parameters:
                ///   - body: Received HTTP response body
                public init(body: Operations.getProfileById.Output.Ok.Body) {
                    self.body = body
                }
            }
            /// Success.
            ///
            /// - Remark: Generated from `#/paths//v2/profiles/{profileId}/get(getProfileById)/responses/200`.
            ///
            /// HTTP response code: `200 ok`.
            case ok(Operations.getProfileById.Output.Ok)
            /// The associated value of the enum case if `self` is `.ok`.
            ///
            /// - Throws: An error if `self` is not `.ok`.
            /// - SeeAlso: `.ok`.
            public var ok: Operations.getProfileById.Output.Ok {
                get throws {
                    switch self {
                    case let .ok(response):
                        return response
                    default:
                        try throwUnexpectedResponseStatus(
                            expectedStatus: "ok",
                            response: self
                        )
                    }
                }
            }
            /// Undocumented response.
            ///
            /// A response with a code that is not documented in the OpenAPI document.
            case undocumented(statusCode: Swift.Int, OpenAPIRuntime.UndocumentedPayload)
        }
        @frozen public enum AcceptableContentType: AcceptableProtocol {
            case json
            case other(Swift.String)
            public init?(rawValue: Swift.String) {
                switch rawValue.lowercased() {
                case "application/json":
                    self = .json
                default:
                    self = .other(rawValue)
                }
            }
            public var rawValue: Swift.String {
                switch self {
                case let .other(string):
                    return string
                case .json:
                    return "application/json"
                }
            }
            public static var allCases: [Self] {
                [
                    .json
                ]
            }
        }
    }
}
